name: CI/CI-pre-onboarding-12th-2

on:
  push:
    branch: -main

jobs:
  cicd:
    runs-on: ubuntu-latest
    step:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - run: npm ci
      #- run: npm run test
      - run: npm run build
      - name: deploy to s3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }} # 버킷 이름
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # aws 액세스 키 아이디
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # aws 액세스 키
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'build'
